on:
  push:
    branches:
      - '*'

name: Create Latest Release For Branch On Tag
jobs:
  deploy:
    name: generate release
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v1
      - name: make script
        run: cd src && ./gsht.sh gsht.sh --output ../bin/gsht
      - name: extract tag latest
        shell: bash
        run: echo "##[set-output name=tag;]$(git describe --tags --abbrev=0 HEAD | sed 's/-.*//g')"
        id: extract
      - name: create draft release
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract.outputs.tag }}-latest+${{ github.head_ref || github.ref_name }}
          rm: true
          files: |
            ./bin/*
