on:
  push:
    branches:
      - '*'

name: Create Draft
jobs:
  deploy:
    name: generate release
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v1
      - name: make script
        run: cd src && ./gsht.sh gsht.sh --output ../bin/gsht
      - name: create draft release
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: draft-${{ github.ref }}
          rm: true
          files: |
            ./bin/*
