on:
  push:
    tags:
      - 'v*'
      - '!nightly'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: make script
        run: cd src && ./gsht.sh gsht.sh --output ../bin/gsht
      - name: create tag release
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag:  ${{ github.ref }}
          rm: true
          files: |
            ./bin/*
          draft: false
          prerelease: false